version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: smart-door-backend
    ports:
      - "4000:4000"
    env_file:
      - .env  # เปลี่ยนให้อ่านจาก root folder (ไฟล์เดียวกัน)
    networks:
      - ecpproduct
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: smart-door-frontend
    ports:
      - "4001:80"
    env_file:
      - .env  # เปลี่ยนให้อ่านจาก root folder เช่นกัน
    depends_on:
      - backend
    networks:
      - ecpproduct
    restart: unless-stopped

networks:
  ecpproduct:
    driver: bridge